#!/usr/bin/env bash

echo
./Middleware "$1" &
pid=$!

sleep 2

wrk 'https://localhost:5001/?foo[bar]=baz' \
  -d 3 \
  -c 50 \
  -t 8 \
  | grep 'Requests/sec' \
  | awk '{ print "  " $2 }'

kill $pid
